name: qr_innovations

version: 1.0.12+13

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  connectivity_plus:
  google_fonts:
  flutter_riverpod:
  http:
  shared_preferences:
  intl:
#  skeletons:
  firebase_core: ^3.6.0
  firebase_analytics:
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  cached_network_image:
  permission_handler:
  url_launcher:
  package_info_plus:
  device_info_plus:
  pinput: ^5.0.0
  flutter_svg: ^2.0.9
  image_picker: ^1.0.5
  zego_uikit: ^2.22.2
  launch_review: ^3.0.1
  zego_uikit_prebuilt_call: ^4.9.0
  zego_uikit_signaling_plugin: ^2.7.6
  faker: ^2.1.0
  flutter_styled_toast: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis:
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash:
  change_app_package_name:

# flutter pub run flutter_launcher_icons
flutter_icons:
  image_path: "assets/QrCall_logo.png"
  android: true
  ios: true
  adaptive_icon_foreground: "assets/QrCall_foreground.png"
  remove_alpha_ios: true

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  background_image: "assets/images/splash_screen.png"
  android: true
  ios: true

# flutter pub run change_app_package_name:main com.new.package.name

flutter:
  uses-material-design: true

  assets:
    - assets/
